library(xts)
library(PerformanceAnalytics)

DATA_FOLDER <- 'C:\\Users\\damia\\ResilioSync\\FXBootcamp'

prices_from_resilio <- function(filename, date_format="%Y%m%d") {
  prices = read.table(paste0(DATA_FOLDER, '/RiskPremia', '/', filename, '.csv'), header=TRUE, sep=",", row.names="Date") 
  #rownames(prices) = as.Date(rownames(prices), format = date_format)
  prices <- as.xts(prices, order.by = as.Date(rownames(prices), format = date_format))
  
  # calculate returns
  returns <- Return.calculate(prices$Close)
  #returns = (prices$Close - stats::lag(prices$Close)) / abs(stats::lag(prices$Close))
  # this is equivalent to returns <- exp(diff(log(prices$Close))) - 1
  
  prices$Cum_Return = rep(1, length(prices$Close))
  prices$Cum_Return[-1] = cumprod(1+returns[-1])
  
  return(prices)
}

# US Equity price series generated from VFINX mutual fund prices
EQ_US_df <- prices_from_resilio('VFINX')
EQ_US <- EQ_US_df$Cum_Return

# US Bond total return index generated from VBMFX mutual fund prices
BOND_US_df <- prices_from_resilio('VBMFX')
BOND_US <- BOND_US_df$Cum_Return

# make extended gold data
source(paste0(DATA_FOLDER, '/Code/risk-premia/gold_processing.R'))

# Gold total return index generated by extending GSCI Gold index back with Gold spot prices
GOLD_df <- read.table(paste0(DATA_FOLDER, '/RiskPremia/extended_GCSI.csv'), header=TRUE, sep=",")
GOLD <- as.xts(GOLD_df$Cum_Ret, order.by = as.Date(GOLD_df[,1]))

# Treasury bill returns from VFISX mutual fund prices
TBILL_US_df <- prices_from_resilio('VFISX')
TBILL_US <- TBILL_US_df$Cum_Return

# Merge data for plotting
# GOLD series has observations on days the mututal funds did not trade and vice versa.
# We decide to deal with this by  left joining the gold series to the combined equity and bond series
# and carrying forward any NAs in the GOLD series.
indexes <- na.omit(na.locf(merge(merge(EQ_US, BOND_US, TBILL_US), GOLD, join = 'left')))
colnames(indexes) <- c('EQ_US','BOND_US', 'TBILL_US', 'GOLD')

# Calculate daily, weekly and monthly discrete returns
returns_daily <- na.omit(Return.calculate(indexes, method = 'discrete'))
returns_monthly <- na.omit(Return.calculate(indexes[endpoints(indexes, on='months')], method = 'discrete'))


charts.PerformanceSummary(returns_daily, main = 'Asset Class Performance')
chart.Boxplot(returns_monthly)

par(mfrow=c(1,4))
chart.Histogram(returns_monthly[,1], methods = 'add.centered')
chart.Histogram(returns_monthly[,2], methods = 'add.centered')
chart.Histogram(returns_monthly[,3], methods = 'add.centered')
chart.Histogram(returns_monthly[,4], methods = 'add.centered')

table.AnnualizedReturns(returns_monthly)

table.DownsideRisk(returns_monthly)

par(mfrow=c(1,3))
chart.ACF(returns_monthly$EQ_US, main=c('EQ_US Monthly'))
chart.ACF(returns_monthly$BOND_US, main=c('BOND_US Monthly'))
chart.ACF(returns_monthly$GOLD, main=c('GOLD Monthly'))

par(mfrow=c(1,3))
chart.ACF(returns_daily$EQ_US, main=c('EQ_US Daily'))
chart.ACF(returns_daily$BOND_US, main=c('BOND_US Daily'))
chart.ACF(returns_daily$GOLD, main=c('GOLD Daily'))

chart.RiskReturnScatter(returns_monthly)

charts.RollingPerformance(returns_monthly, width = 6, legend.loc = 'topleft')
charts.RollingPerformance(returns_monthly, width = 12, legend.loc = 'topleft')
charts.RollingPerformance(returns_monthly, width = 18, legend.loc = 'topleft')

chart.RollingCorrelation(returns_daily[,1], returns_daily[,2], width = 252)
chart.RollingCorrelation(returns_daily[,1], returns_daily[,4], width = 252)

EW_portfolio <- Return.portfolio(returns_monthly, weights = c(0.25,0.25,0.25,0.25), rebalance_on = 'months')
EW_compare <- merge(EW_portfolio, returns_monthly[,'EQ_US'], join='left')
table.AnnualizedReturns(EW_compare)

charts.PerformanceSummary(EW_portfolio, main = 'US EW Risk Premia Performance')


# Non-US Developed Markets Equity total return index generated from XMSC MSCI index prices
EQ_NONUS_DEV_df <- prices_from_resilio('XMSC-F') 
EQ_NONUS_DEV <- EQ_NONUS_DEV_df$Cum_Return

# Emerging Markets Equity total return index generated from MXEA MSCI index prices
EQ_EMER_df <- prices_from_resilio('MXEA-F')  
EQ_EMER <- EQ_EMER_df$Cum_Return

# International Bonds total return index generated from Benham International Bond Fund prices
BOND_NONUS_df <- prices_from_resilio('BEGBX')
BOND_NONUS <- BOND_NONUS_df$Cum_Return

# Emerging Markets Bond total return index generated from T Rowe Price Emerging Markets Bond Fund
BOND_EMER_df <- prices_from_resilio('PREMX') 
BOND_EMER <- BOND_EMER_df$Cum_Return

# Merge data for plotting
nonus_index <- na.omit(na.locf(merge(EQ_NONUS_DEV, BOND_NONUS, EQ_EMER, BOND_EMER)))
colnames(nonus_index) <- c('EQ_NONUS_DEV', 'BOND_NONUS', 'EQ_EMER', 'BOND_EMER')

# Keep data from 2013 aside. (Note it's not a very good OOS period, as we know what happened!)
nonus_sample <- nonus_index['::2012']

# Calculate daily, weekly and monthly discrete returns
nonus_returns_monthly <- na.omit(Return.calculate(nonus_sample[endpoints(nonus_sample, on='months')], method = 'discrete'))

charts.PerformanceSummary(nonus_returns_monthly, wealth.index = TRUE, legend.loc = 'topleft', main = 'International Asset Performance Summary')

nonus_EW_portfolio <- Return.portfolio(nonus_returns_monthly, weights = c(0.25,0.25,0.25,0.25), rebalance_on = 'months')
table.AnnualizedReturns(nonus_EW_portfolio)
